default:
  image: php:8.0-fpm

before_script:
  - echo 'Downloading and installing PHP docker dependencies..'
  - apt-get update && apt-get install -y zip libzip-dev unzip git libfreetype6-dev libjpeg62-turbo-dev libxslt-dev libpng-dev > /dev/null && docker-php-ext-install -j$(nproc) gd xsl intl zip > /dev/null
  - echo 'Downloading and installing composer...';
  - curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install

static_analysis:
  script:
    - echo 'Analyzing..' && php --version && php -d memory_limit=512M vendor/bin/phpstan analyse -c phpstan.neon
